---
AWSTemplateFormatVersion: "2010-09-09"
Description: "IAM Role for deploy by CloudFormation"
# CloudFormationでスタックを反映するときに使うIAMロール

Resources:
  CloudFormationDeployRole:
    Type: "AWS::IAM::Role"
    Properties: 
      RoleName: "CloudFormationDeployerRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "cloudformation.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Description: "IAM Role for deploy by CloudFormation"
      ManagedPolicyArns: 
        - "arn:aws:iam::aws:policy/PowerUserAccess"
        - "arn:aws:iam::aws:policy/IAMReadOnlyAccess"

  # TODO: ポリシーが適切じゃなさそうなので確認する
  CloudFormationDeployRolePolicy:
    DependsOn: "CloudFormationDeployRole"
    Type: "AWS::IAM::Policy"
    Properties: 
      PolicyName: "AllowConfigurateIAMRole"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action: 
              - "iam:AttachRolePolicy"
              - "iam:CreatePolicy"
              - "iam:CreatePolicyVersion"
              - "iam:CreateRole"
              - "iam:DeletePolicy"
              - "iam:DeletePolicyVersion"
              - "iam:DeleteRole"
              - "iam:DeleteRolePermissionsBoundary"
              - "iam:DeleteRolePolicy"
              - "iam:DetachRolePolicy"
              - "iam:PutRolePermissionsBoundary"
              - "iam:PutRolePolicy"
              - "iam:RemoveRoleFromInstanceProfile"
              - "iam:SetDefaultPolicyVersion"
              - "iam:TagPolicy"
              - "iam:TagRole"
              - "iam:UntagInstanceProfile"
              - "iam:UntagPolicy"
              - "iam:UntagRole"
              - "iam:UpdateAssumeRolePolicy"
              - "iam:UpdateRole"
              - "iam:UpdateRoleDescription"
            Resource: '*'
      Roles:
        - !Ref CloudFormationDeployRole
